
services:
    fbpixiv:
        container_name: pixivfbapi
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - TZ=Asia/Ho_Chi_Minh
        volumes: 
            - "/etc/timezone:/etc/timezone:ro" 
            - "/etc/localtime:/etc/localtime:ro"
        restart: always
